project:
  type: website
  output-dir: docs

website:
  title: "Morgane Hoffmann"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href : research.qmd
        text: Research
      - href : about.qmd
        text: Curriculum

format:
  html:
    theme: flatly
    css: styles.css
    toc: true
    fontsize: 1.05em
    mainfont: system-ui, -apple-system, "Segoe UI", Roboto, sans-serif



